package com.nito.fantasy.model.dynamodb;

import java.time.LocalDateTime;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverted;
import com.nito.fantasy.util.LocalDateTimeConverter;

@DynamoDBTable(tableName = "FantasyPlayerHistory")
public class FantasyPlayerHistoryDB {
	private String id;
	private String leagueId;
	private String playerId;
	private String playerName;
	private LocalDateTime date;
	private String operation;
	private Integer money;

    public FantasyPlayerHistoryDB() {
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }
    
    public void setId(String id) {
		this.id = id;
	}

    @DynamoDBAttribute
	public String getLeagueId() {
		return leagueId;
	}

	public void setLeagueId(String leagueId) {
		this.leagueId = leagueId;
	}

    @DynamoDBAttribute
	public String getPlayerId() {
		return playerId;
	}

	public void setPlayerId(String playerId) {
		this.playerId = playerId;
	}

	@DynamoDBAttribute
	public String getPlayerName() {
		return playerName;
	}

	public void setPlayerName(String playerName) {
		this.playerName = playerName;
	}

	@DynamoDBAttribute
	@DynamoDBTypeConverted( converter = LocalDateTimeConverter.class )
	public LocalDateTime getDate() {
		return date;
	}

	public void setDate(LocalDateTime date) {
		this.date = date;
	}

	@DynamoDBAttribute
	public String getOperation() {
		return operation;
	}

	public void setOperation(String operation) {
		this.operation = operation;
	}

	@DynamoDBAttribute
	public Integer getMoney() {
		return money;
	}

	public void setMoney(Integer money) {
		this.money = money;
	}
}
