package com.nito.fantasy.model.dynamodb;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.nito.fantasy.dto.Player;

@DynamoDBTable(tableName = "FantasyPlayer")
public class FantasyPlayerDB {
	private String id;

	private String playerName;

	private String playerImage;

	private String playerTeamName;

	private String playerTeamImage;

	private Integer playerPositionId;

	private Integer playerPoints;

	private Double playerAveragePoints;

	private Integer playerPointsAA;

	private Integer playerGamesPlayed;

	private Integer playerMinutesPlayed;

	private Integer playerMarketValue;

	private Integer playerMarketValueYesterday;

	private Integer playerMarketValueYesterday2;

	public FantasyPlayerDB() {
	}

	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@DynamoDBAttribute
	public String getPlayerName() {
		return playerName;
	}

	public void setPlayerName(String playerName) {
		this.playerName = playerName;
	}

	@DynamoDBAttribute
	public Integer getPlayerPoints() {
		return playerPoints;
	}

	public void setPlayerPoints(Integer playerPoints) {
		this.playerPoints = playerPoints;
	}

	@DynamoDBAttribute
	public Integer getPlayerPointsAA() {
		return playerPointsAA;
	}

	public void setPlayerPointsAA(Integer playerPointsAA) {
		this.playerPointsAA = playerPointsAA;
	}

	@DynamoDBAttribute
	public Integer getPlayerMarketValue() {
		return playerMarketValue;
	}

	public void setPlayerMarketValue(Integer playerMarketValue) {
		this.playerMarketValue = playerMarketValue;
	}

	@DynamoDBAttribute
	public String getPlayerImage() {
		return playerImage;
	}

	public void setPlayerImage(String playerImage) {
		this.playerImage = playerImage;
	}

	@DynamoDBAttribute
	public String getPlayerTeamName() {
		return playerTeamName;
	}

	public void setPlayerTeamName(String playerTeamName) {
		this.playerTeamName = playerTeamName;
	}

	@DynamoDBAttribute
	public String getPlayerTeamImage() {
		return playerTeamImage;
	}

	public void setPlayerTeamImage(String playerTeamImage) {
		this.playerTeamImage = playerTeamImage;
	}

	@DynamoDBAttribute
	public Integer getPlayerPositionId() {
		return playerPositionId;
	}

	public void setPlayerPositionId(Integer playerPositionId) {
		this.playerPositionId = playerPositionId;
	}

	public Player convertToDto() {
		Player newPlayer = new Player();
		newPlayer.setPlayerId(this.id);
		newPlayer.setManagerName("-");
		newPlayer.setPlayerName(this.playerName);
		newPlayer.setPlayerPoints(this.playerPoints);
		newPlayer.setPlayerAveragePoints(this.playerAveragePoints);
		newPlayer.setPlayerPointsAA(this.playerPointsAA);
		newPlayer.setPlayerValue(this.playerMarketValue);
		newPlayer.setPlayerImage(this.playerImage);
		newPlayer.setPlayerTeamName(this.playerTeamName);
		newPlayer.setPlayerTeamImage(this.playerTeamImage);
		newPlayer.setPlayerPosition(this.playerPositionId);
		newPlayer.setUpDownYesterday(this.playerMarketValueYesterday, this.playerMarketValueYesterday2);
		newPlayer.setPlayerGamesPlayed(this.playerGamesPlayed);
		newPlayer.setPlayerMinutesPlayed(this.playerMinutesPlayed);
		newPlayer.setPlayerAveragePointsGame();
		newPlayer.setPlayerAveragePointsMinutes();
		newPlayer.setPlayerAveragePointsMinutesGame();
		return newPlayer;
	}

	@DynamoDBAttribute
	public Integer getPlayerMarketValueYesterday() {
		return playerMarketValueYesterday;
	}

	public void setPlayerMarketValueYesterday(Integer playerMarketValueYesterday) {
		this.playerMarketValueYesterday = playerMarketValueYesterday;
	}

	@DynamoDBAttribute
	public Integer getPlayerMarketValueYesterday2() {
		return playerMarketValueYesterday2;
	}

	public void setPlayerMarketValueYesterday2(Integer playerMarketValueYesterday2) {
		this.playerMarketValueYesterday2 = playerMarketValueYesterday2;
	}

	@DynamoDBAttribute
	public Double getPlayerAveragePoints() {
		return playerAveragePoints;
	}

	@DynamoDBAttribute
	public void setPlayerAveragePoints(Double playerAveragePoints) {
		this.playerAveragePoints = playerAveragePoints;
	}

	@DynamoDBAttribute
	public Integer getPlayerGamesPlayed() {
		return playerGamesPlayed;
	}

	public void setPlayerGamesPlayed(Integer playerGamesPlayed) {
		this.playerGamesPlayed = playerGamesPlayed;
	}

	@DynamoDBAttribute
	public Integer getPlayerMinutesPlayed() {
		return playerMinutesPlayed;
	}

	public void setPlayerMinutesPlayed(Integer playerMinutesPlayed) {
		this.playerMinutesPlayed = playerMinutesPlayed;
	}
}
