package com.nito.fantasy.model.dynamodb;

import java.time.LocalDateTime;

import org.apache.log4j.Logger;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverted;
import com.nito.fantasy.dto.Player;
import com.nito.fantasy.util.Formatter;
import com.nito.fantasy.util.LocalDateTimeConverter;

@DynamoDBTable(tableName = "FantasyLeaguePlayer")
public class FantasyLeaguePlayerDB {
	private static final Logger logger = Logger.getLogger(FantasyLeaguePlayerDB.class);

	private String id;

	private String leagueId;

	private String playerId;

	private String playerName;

	private String playerImage;

	private String playerTeam;

	private String playerTeamImage;

	private Integer playerPositionId;

	private String managerName;

	private String teamId;

	private Integer playerPoints;

	private Double playerAveragePoints;

	private Integer playerPointsAA;

	private Integer playerGamesPlayed;

	private Integer playerMinutesPlayed;

	private Integer playerMarketValue;

	private Integer playerMarketValueYesterday;

	private Integer playerMarketValueYesterday2;

	private Integer playerBuyoutClause;

	private LocalDateTime playerEndBuyoutClause;

	private LocalDateTime playerPurchaseDate;

	private Integer playerPurchaseAmount;

	private Integer playerMarketValuePurchaseDate;

	public FantasyLeaguePlayerDB() {
	}

	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@DynamoDBAttribute
	public String getLeagueId() {
		return leagueId;
	}

	public void setLeagueId(String leagueId) {
		this.leagueId = leagueId;
	}

	@DynamoDBAttribute
	public String getPlayerId() {
		return playerId;
	}

	public void setPlayerId(String playerId) {
		this.playerId = playerId;
	}

	@DynamoDBAttribute
	public String getPlayerName() {
		return playerName;
	}

	public void setPlayerName(String playerName) {
		this.playerName = playerName;
	}

	@DynamoDBAttribute
	public String getManagerName() {
		return managerName;
	}

	public void setManagerName(String managerName) {
		this.managerName = managerName;
	}

	@DynamoDBAttribute
	public Integer getPlayerPoints() {
		return playerPoints;
	}

	public void setPlayerPoints(Integer playerPoints) {
		this.playerPoints = playerPoints;
	}

	@DynamoDBAttribute
	public Integer getPlayerPointsAA() {
		return playerPointsAA;
	}

	public void setPlayerPointsAA(Integer playerPointsAA) {
		this.playerPointsAA = playerPointsAA;
	}

	@DynamoDBAttribute
	public Integer getPlayerMarketValue() {
		return playerMarketValue;
	}

	public void setPlayerMarketValue(Integer playerMarketValue) {
		this.playerMarketValue = playerMarketValue;
	}

	@DynamoDBAttribute
	public Integer getPlayerBuyoutClause() {
		return playerBuyoutClause;
	}

	public void setPlayerBuyoutClause(Integer playerBuyoutClause) {
		this.playerBuyoutClause = playerBuyoutClause;
	}

	@DynamoDBAttribute
	@DynamoDBTypeConverted(converter = LocalDateTimeConverter.class)
	public LocalDateTime getPlayerEndBuyoutClause() {
		return playerEndBuyoutClause;
	}

	public void setPlayerEndBuyoutClause(LocalDateTime playerEndBuyoutClause) {
		this.playerEndBuyoutClause = playerEndBuyoutClause;
	}

	@DynamoDBAttribute
	@DynamoDBTypeConverted(converter = LocalDateTimeConverter.class)
	public LocalDateTime getPlayerPurchaseDate() {
		return playerPurchaseDate;
	}

	public void setPlayerPurchaseDate(LocalDateTime playerPurchaseDate) {
		this.playerPurchaseDate = playerPurchaseDate;
	}

	@DynamoDBAttribute
	public Integer getPlayerPurchaseAmount() {
		return playerPurchaseAmount;
	}

	public void setPlayerPurchaseAmount(Integer playerPurchaseAmount) {
		this.playerPurchaseAmount = playerPurchaseAmount;
	}

	@DynamoDBAttribute
	public Integer getPlayerMarketValuePurchaseDate() {
		return playerMarketValuePurchaseDate;
	}

	public void setPlayerMarketValuePurchaseDate(Integer playerMarketValuePurchaseDate) {
		this.playerMarketValuePurchaseDate = playerMarketValuePurchaseDate;
	}

	@DynamoDBAttribute
	public Integer getPlayerMarketValueYesterday() {
		return playerMarketValueYesterday;
	}

	public void setPlayerMarketValueYesterday(Integer playerMarketValueYesterday) {
		this.playerMarketValueYesterday = playerMarketValueYesterday;
	}

	@DynamoDBAttribute
	public String getPlayerImage() {
		return playerImage;
	}

	public void setPlayerImage(String playerImage) {
		this.playerImage = playerImage;
	}

	@DynamoDBAttribute
	public String getPlayerTeam() {
		return playerTeam;
	}

	public void setPlayerTeam(String playerTeam) {
		this.playerTeam = playerTeam;
	}

	@DynamoDBAttribute
	public String getPlayerTeamImage() {
		return playerTeamImage;
	}

	public void setPlayerTeamImage(String playerTeamImage) {
		this.playerTeamImage = playerTeamImage;
	}

	@DynamoDBAttribute
	public Integer getPlayerPositionId() {
		return playerPositionId;
	}

	public void setPlayerPositionId(Integer playerPositionId) {
		this.playerPositionId = playerPositionId;
	}

	public Player convertToDto() {
		Player newPlayer = new Player();
		newPlayer.setPlayerId(this.playerId);
		newPlayer.setPlayerName(this.playerName);
		newPlayer.setManagerName(Formatter.parseNull(this.managerName));
		newPlayer.setTeamId(this.teamId);
		newPlayer.setPlayerPoints(this.playerPoints);
		newPlayer.setPlayerAveragePoints(this.playerAveragePoints);
		newPlayer.setPlayerPointsAA(this.playerPointsAA);
		newPlayer.setPlayerValue(this.playerMarketValue);
		newPlayer.setPlayerBuyoutClause(this.playerBuyoutClause);
		newPlayer.setPlayerEndBuyoutClause(this.playerEndBuyoutClause);
		newPlayer.setUpDownBuyoutClause();
		newPlayer.setUpDownYesterday(this.playerMarketValueYesterday, this.playerMarketValueYesterday2);
		newPlayer.setUpDownPurchaseDate(this.playerPurchaseDate, this.playerPurchaseAmount, this.playerMarketValuePurchaseDate);
		newPlayer.setPlayerImage(this.playerImage);
		newPlayer.setPlayerTeamName(this.playerTeam);
		newPlayer.setPlayerTeamImage(this.playerTeamImage);
		newPlayer.setPlayerPosition(this.playerPositionId);
		newPlayer.setPlayerGamesPlayed(this.playerGamesPlayed);
		newPlayer.setPlayerMinutesPlayed(this.playerMinutesPlayed);
		logger.info(this.playerName + "(" + this.playerPoints + ") -> " + "games:" + this.playerGamesPlayed + ", minutes:"
				+ this.playerMinutesPlayed);
		newPlayer.setPlayerAveragePointsGame();
		newPlayer.setPlayerAveragePointsMinutes();
		newPlayer.setPlayerAveragePointsMinutesGame();
		return newPlayer;
	}

	@DynamoDBAttribute
	public String getTeamId() {
		return teamId;
	}

	public void setTeamId(String teamId) {
		this.teamId = teamId;
	}

	@DynamoDBAttribute
	public Integer getPlayerMarketValueYesterday2() {
		return playerMarketValueYesterday2;
	}

	public void setPlayerMarketValueYesterday2(Integer playerMarketValueYesterday2) {
		this.playerMarketValueYesterday2 = playerMarketValueYesterday2;
	}

	@DynamoDBAttribute
	public Double getPlayerAveragePoints() {
		return playerAveragePoints;
	}

	public void setPlayerAveragePoints(Double playerAveragePoints) {
		this.playerAveragePoints = playerAveragePoints;
	}

	@DynamoDBAttribute
	public Integer getPlayerGamesPlayed() {
		return playerGamesPlayed;
	}

	public void setPlayerGamesPlayed(Integer playerGamesPlayed) {
		this.playerGamesPlayed = playerGamesPlayed;
	}

	@DynamoDBAttribute
	public Integer getPlayerMinutesPlayed() {
		return playerMinutesPlayed;
	}

	public void setPlayerMinutesPlayed(Integer playerMinutesPlayed) {
		this.playerMinutesPlayed = playerMinutesPlayed;
	}
}
