package com.nito.fantasy.model.dynamodb;

import java.time.LocalDate;
import java.time.LocalDateTime;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverted;
import com.nito.fantasy.util.LocalDateConverter;
import com.nito.fantasy.util.LocalDateTimeConverter;

@DynamoDBTable(tableName = "FantasyPlayerMarket")
public class FantasyPlayerMarketDB {
	private String id;
	private String playerId;
	private LocalDate date;
	private Integer marketValue;

    public FantasyPlayerMarketDB() {
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }
    
    public void setId(String id) {
		this.id = id;
	}

    @DynamoDBAttribute
	public String getPlayerId() {
		return playerId;
	}

	public void setPlayerId(String playerId) {
		this.playerId = playerId;
	}

    @DynamoDBAttribute
	@DynamoDBTypeConverted( converter = LocalDateConverter.class )
	public LocalDate getDate() {
		return date;
	}

	public void setDate(LocalDate date) {
		this.date = date;
	}

	public Integer getMarketValue() {
		return marketValue;
	}

	public void setMarketValue(Integer marketValue) {
		this.marketValue = marketValue;
	}
}
