package com.nito.fantasy.model.dynamodb;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverted;
import com.nito.fantasy.dto.Player;
import com.nito.fantasy.model.marca.FantasyHistory;
import com.nito.fantasy.model.marca.FantasyPlayerMarket;
import com.nito.fantasy.model.marca.FantasyTeam;
import com.nito.fantasy.util.Formatter;
import com.nito.fantasy.util.LocalDateTimeConverter;

@DynamoDBTable(tableName = "FantasyPlayer")
public class FantasyPlayerDB {
	private String id;
	private String playerName;
	private String playerImage;
	private String playerTeamName;
	private String playerTeamImage;
	private Integer playerPositionId;
	private Integer playerPoints;
	private Integer playerPointsAA;
	private Integer playerMarketValue;
	private Integer playerMarketValueYesterday;

    public FantasyPlayerDB() {
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }
    
    public void setId(String id) {
		this.id = id;
	}

	@DynamoDBAttribute
	public String getPlayerName() {
		return playerName;
	}

	public void setPlayerName(String playerName) {
		this.playerName = playerName;
	}

	@DynamoDBAttribute
	public Integer getPlayerPoints() {
		return playerPoints;
	}

	public void setPlayerPoints(Integer playerPoints) {
		this.playerPoints = playerPoints;
	}

	@DynamoDBAttribute
	public Integer getPlayerPointsAA() {
		return playerPointsAA;
	}

	public void setPlayerPointsAA(Integer playerPointsAA) {
		this.playerPointsAA = playerPointsAA;
	}

	@DynamoDBAttribute
	public Integer getPlayerMarketValue() {
		return playerMarketValue;
	}

	public void setPlayerMarketValue(Integer playerMarketValue) {
		this.playerMarketValue = playerMarketValue;
	}

    @DynamoDBAttribute
    public String getPlayerImage() {
		return playerImage;
	}

	public void setPlayerImage(String playerImage) {
		this.playerImage = playerImage;
	}

    @DynamoDBAttribute
	public String getPlayerTeamName() {
		return playerTeamName;
	}

	public void setPlayerTeamName(String playerTeamName) {
		this.playerTeamName = playerTeamName;
	}

    @DynamoDBAttribute
	public String getPlayerTeamImage() {
		return playerTeamImage;
	}

	public void setPlayerTeamImage(String playerTeamImage) {
		this.playerTeamImage = playerTeamImage;
	}

    @DynamoDBAttribute
	public Integer getPlayerPositionId() {
		return playerPositionId;
	}

	public void setPlayerPositionId(Integer playerPositionId) {
		this.playerPositionId = playerPositionId;
	}

	public Player convertToDto(){
		Player newPlayer = new Player();
		newPlayer.setPlayerId(this.id);
		newPlayer.setManagerName("-");
		newPlayer.setPlayerName(this.playerName);
		newPlayer.setPlayerPoints(this.playerPoints);
		newPlayer.setPlayerPointsAA(this.playerPointsAA);
		newPlayer.setPlayerValue(this.playerMarketValue);
		newPlayer.setPlayerValueFormatted(Formatter.formatNumber(this.playerMarketValue));
		newPlayer.setPlayerImage(this.playerImage);
		newPlayer.setPlayerTeamName(this.playerTeamName);
		newPlayer.setPlayerTeamImage(this.playerTeamImage);
		newPlayer.setPlayerPosition(this.playerPositionId);
		newPlayer.setUpDownYesterday(this.playerMarketValueYesterday);
    	return newPlayer;
    }

	public Integer getPlayerMarketValueYesterday() {
		return playerMarketValueYesterday;
	}

    @DynamoDBAttribute
	public void setPlayerMarketValueYesterday(Integer playerMarketValueYesterday) {
		this.playerMarketValueYesterday = playerMarketValueYesterday;
	}
}
